# gradle 메모리
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Fabric 버전 (fabricmc.net/develop 기준 26.2)
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# 모드 정보
mod_version=1.0.0
maven_group=com.anti069

# 의존성
fabric_api_version=0.155.2+26.2
